// ============================================================
// SITE DATA — single source of truth for all pages.
// Service detail, case study, blog post, legal, FAQ content
// is generated from these arrays.
// ============================================================

const SERVICES = [
  {
    slug: "website-builds", cat: "Website Builds", title: "Website Builds",
    hero: "Websites designed and built by the studio — then looked after after launch.",
    img: "work/doctor-yachts.png",
    intro: "Royal Eagle builds websites for South Florida businesses. WordPress when it fits, custom when it does not. You own the site. We stay reachable after it ships.",
    bullets: ["Design and build for the work you actually do", "Mobile-friendly pages a person can finish on a phone", "You own the files, the domain, and the accounts", "Analytics when you want them", "Post-launch care available"],
    price: "Custom quote",
    stack: ["WordPress", "HTML", "CSS", "JavaScript"],
    deliverables: ["Live site", "Admin access", "A walkthrough"],
    faqs: [{"q":"How long does a website take?","a":"A straightforward marketing site is often a matter of weeks. Larger work takes longer. We will tell you on the first call."},{"q":"Will I own the website?","a":"Yes. The design, code, content, and accounts are yours."},{"q":"Do you use templates?","a":"We design for the business in front of us. We do not recycle a house layout across clients."},{"q":"What about maintenance after launch?","a":"Optional. Updates, backups, and small edits — see Maintenance, or the WordPress page."}],
  },
  {
    slug: "ai-websites", index: false, cat: "Website Builds", title: "AI Websites",
    hero: "AI on a site only when it helps — not a 24/7 personalization factory.",
    img: "",
    intro: "We use AI in the work when it is useful. We do not sell branded chat, visitor-aware landing pages, or a Pinecone stack as a product line.",
    bullets: ["Honest conversation about whether AI belongs on the site", "Practical help — not a demo theater", "The studio stays accountable"],
    price: "Custom quote",
    stack: ["Claude", "ChatGPT"],
    deliverables: ["A clear recommendation", "Implementation only if it is worth doing"],
    faqs: [{"q":"Do you build AI websites?","a":"We will talk through it. If a chatbot or assistant is the wrong spend, we will say so."},{"q":"Which models do you use?","a":"Usually Claude or ChatGPT when AI is actually in the job. We do not run an enterprise model catalog."}],
  },
  {
    slug: "wordpress-elementor", cat: "Website Builds", title: "WordPress & Elementor",
    hero: "WordPress and Elementor sites you can actually update.",
    img: "work/construction-95.png",
    intro: "We build and maintain WordPress and Elementor sites. The studio is in Lauderhill. No plugin catalog. No invented case metrics.",
    bullets: ["New WordPress sites, including Elementor", "Rebuilds when a theme has gotten away from you", "Editor setup so you can change pages without breaking the layout", "Hosting and email when you want one studio on the hook"],
    price: "Custom quote",
    stack: ["WordPress", "Elementor"],
    deliverables: ["WordPress site", "Editor walkthrough"],
    faqs: [{"q":"Do you still build WordPress sites?","a":"Yes. WordPress and Elementor are a regular part of the work."},{"q":"Can our team update the site?","a":"That is a design goal. If you would rather we handle edits, that is maintenance."},{"q":"Do you maintain WordPress after launch?","a":"Yes. Updates, backups, and small content edits. Call 754-233-4037."}],
  },
  {
    slug: "custom-themes", cat: "Website Builds", title: "Custom Themes",
    hero: "A theme built for your pages — not a premium theme with the logo swapped.",
    img: "work/green-coast.png",
    intro: "When an off-the-shelf theme starts running the brand, we build a theme that fits the pages you actually have. WordPress when that is the CMS. No invented block counts or CI/CD theater.",
    bullets: ["Theme built for your content", "Editors can work without breaking the layout", "You can take it to another host later"],
    price: "Custom quote",
    stack: ["WordPress", "PHP"],
    deliverables: ["Theme files", "A walkthrough"],
    faqs: [{"q":"When does a custom theme make sense?","a":"When a store-bought theme is fighting the brand, or the admin is no longer safe to touch."},{"q":"Will I be locked in?","a":"No. You get the files. You can take them elsewhere."}],
  },
  {
    slug: "ecommerce", cat: "Website Builds", title: "Ecommerce",
    hero: "Shopify or WooCommerce when you need a store that is practical to run.",
    img: "work/florida-impact.png",
    intro: "We build Shopify and WooCommerce stores. Products, checkout, and the pages that sell. We do not sell Shopify Plus, Hydrogen, or ERP integrations as a factory line.",
    bullets: ["Shopify or WooCommerce — we will say which fits", "Products and checkout that a small business can run", "No invented subscription-engine roster"],
    price: "Custom quote",
    stack: ["Shopify", "WooCommerce"],
    deliverables: ["Storefront", "Admin access"],
    faqs: [{"q":"Shopify or WooCommerce?","a":"Shopify is usually simpler to operate. WooCommerce if you already live in WordPress. We will recommend on the call — not from a partner badge."},{"q":"Do you do Shopify Plus or headless commerce?","a":"Not as a productized offer. If a project truly needs that, we will say so — or point you elsewhere."}],
  },
  {
    slug: "domains-hosting", cat: "Infrastructure", title: "Domains & Hosting",
    hero: "Domain, hosting, and SSL — with a person at the studio you can call.",
    img: "",
    intro: "We set up domains, hosting, and SSL for South Florida businesses. When something breaks, you call the studio — not a chatbot. Reviews on Google mention the hosting and email work.",
    bullets: ["Domain and DNS", "Hosting and SSL", "Backups", "A phone that a person answers"],
    price: "Custom quote",
    stack: ["WordPress hosting", "Cloudflare", "DNS"],
    deliverables: ["Live hosting", "Credentials that are yours"],
    faqs: [{"q":"Why not the cheapest host?","a":"Cheap hosting is fine until the site is slow or down. We pick hosting the site can actually live on."},{"q":"Can I leave later?","a":"Yes. You own the domain and the site. We hand over credentials."}],
  },
  {
    slug: "email-services", cat: "Infrastructure", title: "Email Services",
    hero: "Business email set up so it lands in the inbox.",
    img: "",
    intro: "Google Workspace or Microsoft 365, plus SPF, DKIM, and DMARC so mail is not guessed at. Google reviews mention email we fixed. That is the work.",
    bullets: ["Google Workspace or Microsoft 365", "SPF, DKIM, DMARC", "Mailbox move when you are changing hosts"],
    price: "Custom quote",
    stack: ["Google Workspace", "Microsoft 365"],
    deliverables: ["Working business email", "DNS records documented"],
    faqs: [{"q":"Why is mail going to spam?","a":"Usually missing authentication. We fix the DNS and check that mail lands."},{"q":"Google or Microsoft?","a":"Whichever your people already use. We set it up properly either way."}],
  },
  {
    slug: "maintenance", cat: "Infrastructure", title: "Maintenance",
    hero: "Updates, backups, and small edits after launch.",
    img: "work/yellow-plumbing.png",
    intro: "A WordPress or marketing site is not finished the day it goes live. We offer ongoing care as a monthly conversation with the studio — not a productized factory and not a 4-hour SLA we printed to sound large.",
    bullets: ["Core, theme, and plugin updates", "Backups", "Small content edits", "You can call the studio"],
    price: "Custom quote",
    stack: ["WordPress", "Cloudflare"],
    deliverables: ["A site that stays current", "A person who answers"],
    faqs: [{"q":"What is included?","a":"Updates, backups, and small edits. Larger work gets scoped. We reply within one business day."},{"q":"Can I cancel?","a":"Yes. Month-to-month."}],
  },
  {
    slug: "marketing", cat: "Marketing", title: "Marketing",
    hero: "Marketing from the same studio that built the site.",
    img: "work/florida-impact.png",
    intro: "SEO, ads, and the pages that have to convert. Roy stays in the work. Specialists join when a project needs extra hands — and we say so. Not one project manager and a dashboard farm.",
    bullets: ["Local SEO and the site work that supports it", "Google and Meta ads when paid is the right spend", "Copy and pages that match the offer"],
    price: "Custom quote",
    stack: ["GA4", "Google Ads", "Meta"],
    deliverables: ["A plan you can read", "Work you can see"],
    faqs: [{"q":"What is included in marketing?","a":"Whatever we agreed on the call — usually the site, search, and ads a small business actually needs. Custom quote."},{"q":"Who does the work?","a":"Roy. Extra hands when needed, named up front."}],
  },
  {
    slug: "ppc", cat: "Marketing", title: "PPC — Google & Meta",
    hero: "Google and Meta ads with spend billed to you, not marked up.",
    img: "work/capital-business-funding.png",
    intro: "We run Google Ads and Meta campaigns. Media is billed on your card by the platform. We do not claim TikTok, LinkedIn, or a national ads machine as the default offer.",
    bullets: ["Google Ads", "Meta (Facebook and Instagram)", "Tracking that matches the site", "Reporting you can read"],
    price: "Custom quote",
    stack: ["Google Ads", "Meta Business"],
    deliverables: ["Campaigns in your accounts", "Regular written notes"],
    faqs: [{"q":"Do you take a cut of ad spend?","a":"No. Media is billed by Google or Meta to you. We charge for the work."},{"q":"Do you run TikTok and LinkedIn?","a":"Google and Meta are the usual work. Other platforms only if they fit — we will not list a roster we do not run."}],
  },
  {
    slug: "automation", index: false, cat: "Marketing", title: "Automation",
    hero: "Simple connections — forms, email, the next step — when they save real time.",
    img: "",
    intro: "We connect the few tools a small business actually uses. We do not sell Salesforce implementations or a HubSpot practice.",
    bullets: ["Forms that notify the right inbox", "Basic email follow-up", "No invented ROI math"],
    price: "Custom quote",
    stack: ["The tools you already have"],
    deliverables: ["A workflow that runs", "Notes on what it does"],
    faqs: [{"q":"Do you implement Salesforce?","a":"No. If you need that, you need a different shop."}],
  },
  {
    slug: "design", cat: "Marketing", title: "Design",
    hero: "Site design, identity, and the graphics the work needs.",
    img: "work/doctor-yachts.png",
    intro: "Brand and marketing design for the sites we build. Roy stays in the reviews. We do not invent a statistic about how many projects start with a rebrand.",
    bullets: ["Look and layout for the site", "Logo and identity when the job includes it", "Ad and page graphics as needed"],
    price: "Custom quote",
    stack: ["Figma", "Adobe"],
    deliverables: ["Files you can keep using"],
    faqs: [{"q":"Do you do logos, or only websites?","a":"Both, when the job includes it. Many sites start from a logo you already have."},{"q":"Do we get the files?","a":"Yes."}],
  },
  {
    slug: "data", index: false, cat: "Marketing", title: "Data",
    hero: "Analytics that match the site — not a warehouse we do not run.",
    img: "",
    intro: "GA4 and the tracking a marketing site actually needs. We do not architect BigQuery, Segment, or MMM as an offer.",
    bullets: ["GA4 set up so conversions are not double-counted", "A report you can read"],
    price: "Custom quote",
    stack: ["GA4"],
    deliverables: ["Working analytics"],
    faqs: [{"q":"Do you build data warehouses?","a":"No. If you need BigQuery and a modeling layer, that is a different kind of shop."}],
  },
  {
    slug: "ai-strategy", index: false, cat: "AI Consultation", title: "AI Strategy",
    hero: "A conversation about whether AI helps — not a 30-page product.",
    img: "",
    intro: "We will tell you if AI is hype for your situation. We do not sell a four-week, 30-page, CFO-ready roadmap as a packaged engagement.",
    bullets: ["An honest read", "Next steps only if they are real"],
    price: "Custom quote",
    stack: ["Claude", "ChatGPT"],
    deliverables: ["A recommendation in plain English"],
    faqs: [{"q":"What do I get?","a":"A conversation and a written note if you want one. Not a 30-page assessment."}],
  },
  {
    slug: "ai-tools-setup", index: false, cat: "AI Consultation", title: "AI Tools Setup",
    hero: "Help getting Claude or ChatGPT working for the people who will use it.",
    img: "",
    intro: "Practical setup and a short walkthrough. We do not roll out Copilot-plus-Okta enterprise programs as a product line.",
    bullets: ["Account and workspace setup", "A short walkthrough"],
    price: "Custom quote",
    stack: ["Claude", "ChatGPT"],
    deliverables: ["Working access", "Notes your people can keep"],
    faqs: [{"q":"Is this an enterprise rollout?","a":"No. It is help getting the tools you chose working."}],
  },
  {
    slug: "ai-automation", index: false, cat: "AI Consultation", title: "AI Automation",
    hero: "Small AI assists — not an agent platform.",
    img: "",
    intro: "If a repetitive writing or sorting job is wasting your week, we can look at it. We do not ship LangChain agents on Temporal.",
    bullets: ["A clear yes or no", "A small workflow if the yes is real"],
    price: "Custom quote",
    stack: ["Claude", "ChatGPT"],
    deliverables: ["The workflow, if we build one"],
    faqs: [{"q":"Will this replace my team?","a":"No. The point is to take repetitive work off a plate — not to sell a layoff."}],
  },
  {
    slug: "ai-content", index: false, cat: "AI Consultation", title: "AI Content",
    hero: "AI-assisted writing with a human still in it.",
    img: "",
    intro: "We will use AI to draft when it helps, then edit. We do not sell 5x content pipelines or a localization factory.",
    bullets: ["Drafts that still get a human pass", "Your voice, not generic pages"],
    price: "Custom quote",
    stack: ["Claude", "ChatGPT"],
    deliverables: ["Copy you can publish"],
    faqs: [{"q":"Does AI content hurt SEO?","a":"Bad content hurts SEO. Reviewed, useful pages do not. Quality is the question, not the tool."}],
  },
];

const CASE_STUDIES = [
  {
    slug: "doctor-yachts", brand: "Doctor Yachts", tag: "Marine", year: "2026", color: "#1F4A6B",
    url: "https://doctoryachts.com/", location: "Fort Lauderdale, FL",
    services: ["Web Design", "Custom Build"],
    summary: "Mobile boat mechanic serving Fort Lauderdale and South Florida waterways.",
    facts: [["Fort Lauderdale", "Home port"], ["Live site", "doctoryachts.com"], ["Custom build", "Shipped"]],
    shot: "work/doctor-yachts.png",
    imgs: []
  },
  {
    slug: "florida-impact-windows", brand: "Florida Impact Windows & Doors", tag: "Home", year: "2026", color: "#3A6B7A",
    url: "https://floridaimpactwindowsdoors.com/", location: "Hollywood, FL",
    services: ["Web Design", "Marketing site"],
    summary: "Impact windows and doors for Florida homes. Hollywood, FL.",
    facts: [["Hollywood, FL", "Based"], ["Live site", "floridaimpactwindowsdoors.com"], ["Marketing site", "Lead-gen"]],
    shot: "work/florida-impact.png",
    imgs: []
  },
  {
    slug: "construction-95", brand: "Construction 95", tag: "Construction", year: "2026", color: "#3A2C1A",
    url: "https://construction95.com/", location: "Lauderhill / South Florida",
    services: ["Web Design"],
    summary: "Construction 95 LLC. South Florida construction — ground-up, framing, concrete, impact windows and doors, roofing.",
    facts: [["Lauderhill, FL", "Based"], ["(954) 613-2001", "Phone"], ["Live site", "construction95.com"]],
    shot: "work/construction-95.png",
    imgs: []
  },
  {
    slug: "yellow-plumbing", brand: "Yellow Plumbing", tag: "Home services", year: "2026", color: "#6B5A12",
    url: "https://yellowplumbing.com/", location: "Connecticut / New Haven",
    services: ["Web Design"],
    summary: "Connecticut plumbing based in New Haven. Emergency, drain, leak detection, water heater, basement. Founded by Avi Meer.",
    facts: [["New Haven, CT", "Based"], ["Avi Meer", "Founder"], ["Live site", "yellowplumbing.com"]],
    shot: "work/yellow-plumbing.png",
    imgs: []
  },
  {
    slug: "capital-business-funding", brand: "Capital Business Funding", tag: "Finance", year: "2026", color: "#24382C",
    url: "https://capitalbusinessfunding.com/", location: "",
    services: ["Web Design"],
    summary: "Business-funding site for small and mid-size companies. Fast online apply.",
    facts: [["Live site", "capitalbusinessfunding.com"], ["Business funding", "Online apply"]],
    shot: "work/capital-business-funding.png",
    imgs: []
  },
  {
    slug: "green-coast-capital", brand: "Green Coast Capital", tag: "Finance", year: "2026", color: "#2C4A2E",
    url: "https://greencoastcapital.co/", location: "",
    services: ["Web Design"],
    summary: "Business funding site — working capital, live at greencoastcapital.co.",
    facts: [["Live site", "greencoastcapital.co"]],
    shot: "work/green-coast.png",
    imgs: []
  },
];

const BLOG_POSTS = [
  { slug: "ai-website-personalization-2026", title: "How AI personalization is reshaping marketing websites in 2026", cat: "AI", date: "May 18, 2026", read: "8 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1400&q=85", excerpt: "Personalization used to mean swapping a first name into an email subject line. In 2026, it means rendering an entirely different landing page for a returning visitor than a first-time prospect — and AI is the difference." },
  { slug: "wordpress-vs-webflow-2026", title: "WordPress vs Webflow vs Shopify: a 2026 decision framework", cat: "Web Design", date: "May 11, 2026", read: "12 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=1400&q=85", excerpt: "Every quarter someone asks us which platform we'd build their site on. The honest answer is 'it depends' — but here are the four questions that actually decide it." },
  { slug: "lcp-under-1-second", title: "The five changes that took our clients' LCP below 1 second", cat: "Performance", date: "May 04, 2026", read: "10 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=85", excerpt: "Google's Core Web Vitals threshold for 'Good' LCP is 2.5s. Here's the practical work that actually moves a marketing site toward that number." },
  { slug: "claude-for-sales-teams", title: "Five Claude workflows every sales team should be running by now", cat: "AI", date: "Apr 27, 2026", read: "9 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1677756119517-756a188d2d94?w=1400&q=85", excerpt: "The sales-and-AI conversation has moved past 'will it replace SDRs?' to the more useful question: which exact tasks should you offload, and which should stay human?" },
  { slug: "google-ads-2026-changes", title: "What changed in Google Ads in Q1 2026 — and what it means for budgets", cat: "Paid Media", date: "Apr 20, 2026", read: "7 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=1400&q=85", excerpt: "Performance Max keeps getting more autonomous, manual exclusions keep getting weaker, and YouTube placements are eating Search budget. Here's how we're adjusting." },
  { slug: "wcag-22-aa-checklist", title: "The complete WCAG 2.2 AA checklist for marketing websites", cat: "Accessibility", date: "Apr 13, 2026", read: "14 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&q=85", excerpt: "Accessibility isn't a moral nice-to-have any more — it's a legal floor. Here's the full checklist we run every site through before we ship." },
  { slug: "shopify-headless-2026", title: "Should you go headless on Shopify in 2026? A flowchart.", cat: "E-commerce", date: "Apr 06, 2026", read: "8 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1400&q=85", excerpt: "Headless Shopify with Hydrogen is now genuinely production-ready. But it's also genuinely overkill for 80% of stores. Here's how we decide." },
  { slug: "hubspot-vs-salesforce-2026", title: "HubSpot vs Salesforce in 2026 — what changed, and who wins", cat: "Automation", date: "Mar 30, 2026", read: "11 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=85", excerpt: "The old rule was Salesforce for enterprise, HubSpot for SMB. In 2026 the line has moved. Here's where we land in 2026 — and the three questions that decide for any specific business." },
  { slug: "south-florida-local-seo", title: "Local SEO playbook for South Florida service businesses", cat: "SEO", date: "Mar 23, 2026", read: "13 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1400&q=85", excerpt: "Ranking in Broward is not the same problem as ranking in Miami-Dade. Here's a practical playbook for South Florida service businesses." },
  { slug: "klaviyo-flows-roi", title: "The 7 Klaviyo flows that pay for the rest of your marketing stack", cat: "E-commerce", date: "Mar 16, 2026", read: "9 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=1400&q=85", excerpt: "If your store is past the early stage and you are not running these seven flows, you are leaving money on the table." },
  { slug: "ai-content-quality-bar", title: "Where AI content stops being slop — a 2026 quality framework", cat: "AI", date: "Mar 09, 2026", read: "10 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=1400&q=85", excerpt: "AI-written content has earned a bad reputation, mostly deserved. But the gap between 'AI slop' and 'indistinguishable from human' comes down to four production-process changes." },
  { slug: "elementor-vs-gutenberg-2026", title: "Elementor vs Gutenberg in 2026 — and why we still pick both", cat: "WordPress", date: "Mar 02, 2026", read: "8 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1400&q=85", excerpt: "WordPress's block editor has finally matured. Elementor is no longer obviously the right choice. Here's how we pick between them — sometimes on the same project." },
  { slug: "meta-ads-ios-attribution", title: "Meta Ads after the iOS dust settled — the real attribution playbook", cat: "Paid Media", date: "Feb 23, 2026", read: "11 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=1400&q=85", excerpt: "iOS 14.5 was supposed to kill Facebook ads. It didn't — but it changed how you have to measure them. Here's the modeled-attribution setup that actually works." },
  { slug: "design-systems-small-teams", title: "Design systems for teams of one — a pragmatic Figma playbook", cat: "Design", date: "Feb 16, 2026", read: "9 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=1400&q=85", excerpt: "You don't need 200 components to have a design system. Here's the minimum viable Figma library we ship with every brand engagement." },
  { slug: "ga4-server-side-tracking", title: "GA4 server-side tracking — when it's worth the setup", cat: "Data", date: "Feb 09, 2026", read: "10 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=85", excerpt: "Server-side GTM solves the ad-blocker and iOS-tracking problems — but adds a real layer of infrastructure. Here's where the ROI flips positive." },
  { slug: "tiktok-shop-2026", title: "TikTok Shop in 2026 — should you be on it?", cat: "E-commerce", date: "Feb 02, 2026", read: "7 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=1400&q=85", excerpt: "TikTok Shop is no longer experimental. Three categories are winning hard, two are bleeding cash, and one is wildly underrated. Here's our 2026 read." },
  { slug: "wordpress-security-2026", title: "WordPress security in 2026 — the checklist we run on every site", cat: "WordPress", date: "Jan 26, 2026", read: "12 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1400&q=85", excerpt: "WordPress powers 43% of the web, which means it's also the single largest target. Here's the practical security checklist we run on every site we host." },
  { slug: "lead-scoring-models", title: "Building a lead-scoring model that actually predicts revenue", cat: "Automation", date: "Jan 19, 2026", read: "11 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=85", excerpt: "Most lead-scoring models are vibes wrapped in math. Here's how we build models that demonstrably correlate with close rate and contract size." },
  { slug: "rebrand-without-losing-seo", title: "How to rebrand without losing your SEO", cat: "SEO", date: "Jan 12, 2026", read: "9 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1400&q=85", excerpt: "Rebranding usually means a new domain, new URL structure, and a terrifying drop in organic traffic. It doesn't have to. Here's the redirect-and-content map we use." },
  { slug: "agency-pricing-2026", title: "Why we publish our prices in 2026 (and you should too)", cat: "Agency Life", date: "Jan 05, 2026", read: "6 min", author: "Roy Bachar", img: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1400&q=85", excerpt: "Most agencies hide their pricing. We've published ours since 2023, and the data on what it does to lead quality is unambiguous." },
];

const FAQS = [
  { q: "How long does a typical website project take?", a: "A standard marketing site takes 4–8 weeks from kickoff to launch; a large WordPress build or e-commerce site can run 10–16 weeks. We publish a week-by-week schedule on day one and you'll have visibility into every milestone.", group: "Process" },
  { q: "What's included in your monthly maintenance plans?", a: "Updates, backups, and small content edits. The studio stays on the site after launch. Call 754-233-4037 if you want that on a monthly conversation — we reply within one business day.", group: "Maintenance" },
  { q: "Do you work with businesses outside of South Florida?", a: "Yes. The shop is in Lauderhill, just west of Fort Lauderdale, and most clients are nearby. Remote work is fine when the project fits.", group: "Engagement" },
  { q: "Can we keep our existing WordPress host?", a: "Usually yes. We work with most managed WordPress hosts (WP-Engine, Kinsta, Pagely, Pressable). If you're on shared budget hosting that can't support our performance targets, we'll recommend a migration as part of the engagement.", group: "Technical" },
  { q: "How do you price ongoing marketing engagements?", a: "Marketing retainers are scoped to your needs and quoted custom. We bill ad media spend separately, at cost, with full transparency in monthly reports. There are no media markups, no kickbacks, no minimum-spend lock-ins.", group: "Pricing" },
  { q: "Do you offer 30-day money-back guarantees?", a: "Yes — on hosting and maintenance plans we offer a 30-day money-back guarantee. On project work, we structure milestone payments so you can pause or exit the engagement after any completed phase.", group: "Engagement" },
  { q: "Who actually does the work — you or subcontractors?", a: "Roy does the work. When a project needs extra hands — photography, a specialist developer, a specific ad-ops skill — he brings in people he trusts and tells you first. There is no fake org chart.", group: "Process" },
  { q: "Do you use AI in the work?", a: "When it actually helps — drafting, cleanup, research. Not as a costume, and not as a 30-page strategy product we do not sell.", group: "AI" },
  { q: "What is the typical engagement size?", a: "From a monthly maintenance conversation up to a new site. Every engagement is custom-quoted. Call 754-233-4037.", group: "Pricing" },
];

const TEAM = [
  { n: "Roy Bachar", r: "Founder", bio: "Founded Royal Eagle in the Fort Lauderdale area in 2014. Hands-on through every engagement — from first call to post-launch. WordPress, custom sites, marketing, and AI when it actually helps.", img: "" },
];

// Real Google review excerpts (from royaleagleweb.com Google Business profile)
const GOOGLE_REVIEWS = [
  { q: "Professional service! I like the way the project was done, from A to Z. Roy was very responsive and answered all my questions in a timely manner. I asked Roy to refresh how my site looked — he did a great job and added graphics and a new logo as well. If you're looking for a web designer in Fort Lauderdale, give this guy a call.", a: "Verified Google Review", r: "Web design client", stars: 5 },
  { q: "I was looking for a web designer and web developer in Fort Lauderdale for my business and found Roy and his company. He's been extremely helpful with his marketing strategy and website — the communication was great at a very reasonable price.", a: "Verified Google Review", r: "Marketing client", stars: 5 },
  { q: "Roy has been very helpful with marketing and web design consultation and also fixed technical issues I had with my emails that didn't work properly. Highly recommend Roy — solved all my web and hosting issues.", a: "Verified Google Review", r: "Hosting & email client", stars: 5 },
];

const SITE_MAP = [
  { title: "Company", links: [
    { t: "Home", h: "index.html" },
    { t: "Studio", h: "about.html" },
    { t: "Team", h: "team.html" },
    { t: "Testimonials", h: "testimonials.html" },
    { t: "Pricing", h: "pricing.html" },
    { t: "FAQ", h: "faq.html" },
    { t: "Where we work", h: "locations.html" },
    { t: "Contact", h: "contact.html" },
  ]},
  { title: "Services", links: [
    { t: "All services", h: "services.html" },
    { t: "WordPress", h: "wordpress.html" },
    { t: "Contractor websites", h: "contractor-websites.html" },
    { t: "Yacht websites", h: "yacht-websites.html" },
    ...SERVICES.filter((s) => s.index !== false).map((s) => ({ t: s.title, h: `service.html?s=${s.slug}` })),
  ]},
  { title: "Work", links: [
    { t: "Selected work", h: "work.html" },
  ]},
  { title: "Legal", links: [
    { t: "Privacy Policy", h: "legal.html?s=privacy" },
    { t: "Terms of Service", h: "legal.html?s=terms" },
    { t: "Accessibility", h: "legal.html?s=accessibility" },
    { t: "Sitemap", h: "sitemap.html" },
  ]},
  { title: "Other pages", links: [
    { t: "Affiliates", h: "affiliates.html" },
    { t: "White label", h: "white-label.html" },
    { t: "Regions", h: "regions.html" },
    { t: "Blog", h: "blog.html" },
    { t: "Resources", h: "resources.html" },
  ]},
];

// Expose globally
Object.assign(window, { SERVICES, CASE_STUDIES, BLOG_POSTS, FAQS, TEAM, GOOGLE_REVIEWS, SITE_MAP });
